### ISSUE TITLE
Consulta CDR: No se encontro certificadocpegem

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter#77]
Hola, al hacer una consulta en ConsultCdrService->getStatusCdr('20000000001', '01', 'F001', 111)
La sunat me devuelve este error, a alguien le ha sucedido?

> <return><error_message>local:///commons/error/error_utils.xsl:41: xsl:message terminate=yes value='No se encontro certificadocpegem'</error_message><transaction_id>13149501</transaction_id><error_code>0x00230001</error_code><error_subcode>0x00230001</error_subcode><formatted_error_msg>&lt;?xml version="1.0" encoding="UTF-8"?>
> &lt;env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">&lt;env:Body>&lt;env:Fault>&lt;faultcode>env:Client&lt;/faultcode>&lt;faultstring>Internal Error (from client)&lt;/faultstring>&lt;/env:Fault>&lt;/env:Body>&lt;/env:Envelope></formatted_error_msg><error_protocol_reason_phrase>No se encontro certificadocpegem</error_protocol_reason_phrase></return>

**Comment by giansalex** [comment]
Hola @thefantas , debio ser un problema temporal.
![image](https://user-images.githubusercontent.com/14926587/58506287-8af41a00-8154-11e9-9103-9dff15d8f326.png)

**Comment by thefantas** [comment]
Así, ahora este error debería de manejarse en el sistema? tal vez con un try catch?

**Comment by thefantas** [comment]
```
[Tue May 28 13:09:53.338319 2019] [:error] [pid 19431:tid 140340195485440]  PHP Warning:  DOMXPath::query(): Undefined namespace prefix in /home/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php on line 66, referer: https://index.php
[Tue May 28 13:09:53.338531 2019] [:error] [pid 19431:tid 140340195485440]  PHP Warning:  DOMXPath::query(): Invalid expression in /home/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php on line 66, referer: https://index.php
[Tue May 28 13:09:53.338675 2019] [:error] [pid 19431:tid 140340195485440]  PHP Notice:  Trying to get property 'length' of non-object in /home/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php on line 68, referer: https://index.php
[Tue May 28 13:09:53.354784 2019] [:error] [pid 19431:tid 140340195485440]  PHP Fatal error:  Uncaught Exception: Not found cdr response in xml in /home/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php:34, referer: https://index.php
[Tue May 28 13:09:53.354814 2019] [:error] [pid 19431:tid 140340195485440]  Stack trace:, referer: https://index.php
[Tue May 28 13:09:53.354935 2019] [:error] [pid 19431:tid 140340195485440]  #0 /home/vendor/greenter/ws/src/Ws/Services/BaseSunat.php(190): Greenter\\Ws\\Reader\\DomCdrReader->getCdrResponse('<?xml version="...'), referer: https://index.php
[Tue May 28 13:09:53.355070 2019] [:error] [pid 19431:tid 140340195485440]  #1 /home/vendor/greenter/ws/src/Ws/Services/ConsultCdrService.php(76): Greenter\\Ws\\Services\\BaseSunat->extractResponse('PK\\x03\\x04\\x14\\x00\\x08\\x08\\x08\\x00Kc\\xBBN\\x00...'), referer: https://index.php
[Tue May 28 13:09:53.355221 2019] [:error] [pid 19431:tid 140340195485440]  #2 /home/vendor/greenter/ws/src/Ws/Services/ConsultCdrService.php(46): Greenter\\Ws\\Services\\ConsultCdrService->getStatusResult('getStatusCdr', 'statusCdr', '20202020202', '01', 'F001', 9031), referer: https://index.php
[Tue May 28 13:09:53.355327 2019] [:error] [pid 19431:tid 140340195485440]  #3 /home/src/Util.php(75): Greenter\\Ws\\Services\\ConsultCdrService->getStatusCdr('20202020202', '01', 'F001', 9031), referer: https://index.php
[Tue May 28 13:09:53.355474 2019] [:error] [pid 19431:tid 140340195485440]  #4 /home/generador/factura.php(316): Util->getCdrStatu in /home/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php on line 34, referer: https://index.php
```
